### ISSUE TITLE
Corruption at 200% render scale

### ISSUE THREAD

**Issue by Cannonaire** [NVIDIA/Q2RTX#98] opened 2020-12-16 22:44 UTC
I use a 1080p monitor, and with the latest version (1.4.0) I often get massive render artifacting if I set the render scale to 190%~200% (about the same pixel count as 4K). It does this on both Vulkan and Nvidia extensions.

I never encountered this bug on older versions in over 100 hours of playtime, so it is definitely a new bug. I have render scale on hotkeys as I often pause to take screenshots at 200% scale.

It's possible the new version is just more stressful on my 2060 FE (6GB) though, as Afterburner indicates the game is using almost all of my VRAM when this happens.

https://steamcommunity.com/sharedfiles/filedetails/?id=2323314102

**Comment by apanteleev** [comment] 2020-12-17 02:08
Can't reproduce this one either...
I'll try asking someone with a 2060 specifically to try and repro your issues.

**Comment by Cannonaire** [comment] 2020-12-17 02:50
It doesn't happen right away. After playing for awhile, then switching to a higher render scale (as you would for screenshots) it often occurs in heavier scenes. It is much more likely to occur with the new Vulkan extensions than the Nvidia ones. Hope this helps.

**Comment by apanteleev** [comment] 2020-12-17 21:17
I have reproduced the issue with a 6 GB framebuffer GPU. It's related to increased memory consumption of the game, and possibly some memory leaks pointed out in https://github.com/NVIDIA/Q2RTX/pull/84#issuecomment-745595551 which would explain why you're only seeing after playing for a while.

Working on a fix.

**Comment by apanteleev** [comment] 2020-12-18 20:20
Fixed in https://github.com/NVIDIA/Q2RTX/commit/885f3021e556343f02a323644ffeb829bafaa8a5

The game now uses less memory than it did in version 1.3.0.

**Closed** 2021-07-24 00:55 UTC
