### ISSUE TITLE
Default Upscaling is broken in 1.4.0

### ISSUE THREAD

**Issue by Cannonaire** [NVIDIA/Q2RTX#96] opened 2020-12-16 01:53 UTC
If you disable TAA and use a resolution scale lower than 100%, there is no longer any upscaling as of 1.4.0. Instead, the game is rendered in a smaller window with junk and the HUD filling the rest of the screen. This happens in both windowed mode and exclusive fullscreen. It also affects both Vulkan and Nvidia extensions.

https://steamcommunity.com/sharedfiles/filedetails/?id=2322338166

**Comment by Cannonaire** [comment] 2020-12-16 21:21
My system specs:
Intel Core i9-9900K
32GB System RAM
RTX 2060 FE (6GB)
Samsung 970 Pro 1TB SSD
Latest version of Windows 10 (20H2 update)
Latest Nvidia drivers (460.89)

I uninstalled Quake 2 RTX and deleted the game folder from C:\Program Files (x86)\Steam\steamapps\common, then I redownloaded it. Same issue occurred with mostly default settings. I only changed Antialiasing and Resolution scale (same behavior in both Windowed mode and Fullscreen).

https://steamcommunity.com/sharedfiles/filedetails/?id=2323195151
https://steamcommunity.com/sharedfiles/filedetails/?id=2323195123

**Comment by apanteleev** [comment] 2020-12-17 02:04
Sorry, can't reproduce. Upscaling works as intended in all modes, tested on 20 and 30 series RTX GPUs. And I see other users on the Steam forum can't reproduce this either.

Maybe you have some non-default setting in the Nvidia Control Panel that might affect texture sampling? Or some other additional software?...

**Comment by Cannonaire** [comment] 2020-12-17 02:48
I tried default settings in Nvidia control panel, except that GSync was active and vsync was forced on. Other running programs were Bitdefender and Stream Deck software. This issue also never occurred with the previous version. (I have about 100 hours in Quake 2 RTX this year).

I just double-checked, and the issue only presents when TAAU is off and Dynamic Resolution Scale is ON and set lower than 100%. Scaling works normally if DRS is off. I hope that helps more.

**Comment by apanteleev** [comment] 2020-12-18 21:01
> Dynamic Resolution Scale is ON and set lower than 100%

That was it - thanks!

Fixed in https://github.com/NVIDIA/Q2RTX/commit/7330ad715d29c85ceacbae19c34f37a8bef96a75

**Closed** 2021-07-24 00:56 UTC
