### ISSUE TITLE
Animated textures don't work in 1.6

### ISSUE THREAD

**Issue by Paril** [NVIDIA/Q2RTX#185] opened 2022-02-13 14:35 UTC
I was informed that animated textures seem to be broken in 1.6; buttons, for instance, don't animate. We haven't checked func_wall's or non-bmodel animated textures.

**Comment by res2k** [comment] 2022-02-14 07:40
Looks like they fell by the wayside in #171.
Their "animation" (really, choosing material frame based on entity) was handled by the `instance_geometry` shader, but now that's not used any more for brush models...

**Comment by PalmliX** [comment] 2022-02-14 18:34
Just confirmed, created a simple test map, in 1.5 animated textures on a func_wall work correctly, in 1.6 there is no animation. Animated texture on worldspawn works the same in both maps. I uploaded the test map if it helps.
[texanim.zip](https://github.com/NVIDIA/Q2RTX/files/8063147/texanim.zip)

**Comment by apanteleev** [comment] 2022-02-15 21:21
Thank you all for reporting, investigating, and fixing the issue.
I merged the PR in https://github.com/NVIDIA/Q2RTX/commit/73c0b7f202d9a2a88fecf787723f34a50f5a0031

**Closed** 2022-02-23 02:36 UTC
