### ISSUE TITLE
Hard lock-up on Linux with 1.4.0, new NVIDIA 460.32.03 driver and Vulkan ray-tracing

### ISSUE THREAD

**Issue by Gert-dev** [NVIDIA/Q2RTX#102] opened 2021-01-07 18:51 UTC
The new 460.32.03 Linux NVIDIA driver was released as stable today, which [includes support for the new Vulkan ray-tracing extensions](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-460.32.03-Linux). Version 1.4.0 of Q2RTX [includes support for these extensions](https://github.com/NVIDIA/Q2RTX/releases/tag/v1.4.0), so I wanted to try them today with the new driver, but unfortunately the game either renders a black screen or a single frame before locking up.

At times it's hard to switch virtual desktops to get out of the game, as the GNOME desktop starts stuttering heavily while it's stuck. Eventually Q2RTX crashes by itself and the following error is present in the logs:

```
NVRM: Xid (PCI:0000:01:00): 31, pid=4249, Ch 00000036, intr 00000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_5 faulted @ 0x0_00003000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
```

Perhaps I'm doing something wrong, though: I'm using the default settings with the "RTX" renderer and "Prefer KHR extensions". If I switch to the OpenGL renderer, the game works fine, albeit likely without ray-tracing.

**Comment by aaronp24** [comment] 2021-01-07 18:57
Can you please run `sudo nvidia-bug-report.sh` and attach the resulting `nvidia-bug-report.log.gz` file?

**Comment by Gert-dev** [comment] 2021-01-07 19:35
Sure!

[nvidia-bug-report.log.gz](https://github.com/NVIDIA/Q2RTX/files/5783602/nvidia-bug-report.log.gz)

**Comment by aaronp24** [comment] 2021-01-08 01:39
I can't reproduce this problem on my test system, unfortunately. Do you have anything interesting or unusual in your `~/.quake2rtx` config directory that could be affecting it?

**Comment by Gert-dev** [comment] 2021-01-08 14:54
Not that I know of: I've installed the game, booted it, and just started a new game from the menu, which immediately causes this lock up to happen. I hear sound playing in the background of the first level, but the screen gets stuck.

I just tried deleting `.quake2rtx` to be sure, but it had no impact.

I did notice the following in the console that shows while the first level is loading, whilst the screen was frozen (may not be exact since I had to write it down from memory after it crashed):

```
...
Using KHR Ray-tracing
wrong ELF class ELF32: libvklayer_steam_fossilize 
...
```

**Comment by Gert-dev** [comment] 2021-01-17 14:12
Seeing as no one else seems to have any problems with this, I _think_ this can be closed as my GPU being defective (?).

I had the chance to test Quake 2 RTX on Windows as well, and it has exactly the same problem: works with OpenGL, crash when attempting to active ray-tracing. I tried both KHR and NV extensions, both have the same problem. The console log there just says "device lost" and the Windows logs don't appear to mention anything about it.

I also tried another NVIDIA RTX ray-tracing demo (the elevator demo), and it crashes with an error message that the NVIDIA graphics card driver "crashed" and that my driver should be updated (but it already is up-to-date and the very latest one).

**Comment by aaronp24** [comment] 2021-01-19 19:53
Thanks for following up. I'll close this based on your reply. Please let me know if you can still reproduce this with a different GPU that works with other workloads.

**Closed by aaronp24** 2021-01-19 19:53 UTC

**Comment by Gert-dev** [comment] 2021-02-09 17:45
I have some news to report. I came upon the [RayTracingInVulkan](https://github.com/GPSnoopy/RayTracingInVulkan) demo today, which also works on Linux. I've built it from source and it works, except for two specific scenes: both of the "Lucy" ones. Both of those scenes expose pretty much the same crash as I'm experiencing here:

```
kernel: NVRM: Xid (PCI:0000:01:00): 31, pid=32530, Ch 0000000b, intr 00000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_4 faulted @ 0x0_00027000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
kernel: NVRM: GPU Board Serial Number: 
kernel: NVRM: GPU at PCI:0000:01:00: GPU-4f53939a-9adb-6bfb-5325-1d95d50629c7
```

The game itself says this:

```
Vulkan SDK Header Version: 169

Vulkan Instance Extensions: 
- VK_KHR_device_group_creation (0.0.1)
- VK_KHR_display (0.0.23)
- VK_KHR_external_fence_capabilities (0.0.1)
- VK_KHR_external_memory_capabilities (0.0.1)
- VK_KHR_external_semaphore_capabilities (0.0.1)
- VK_KHR_get_display_properties2 (0.0.1)
- VK_KHR_get_physical_device_properties2 (0.0.2)
- VK_KHR_get_surface_capabilities2 (0.0.1)
- VK_KHR_surface (0.0.25)
- VK_KHR_surface_protected_capabilities (0.0.1)
- VK_KHR_xcb_surface (0.0.6)
- VK_KHR_xlib_surface (0.0.6)
- VK_EXT_acquire_xlib_display (0.0.1)
- VK_EXT_debug_report (0.0.9)
- VK_EXT_debug_utils (0.0.2)
- VK_EXT_direct_mode_display (0.0.1)
- VK_EXT_display_surface_counter (0.0.1)
- VK_KHR_wayland_surface (0.0.6)

Vulkan Instance Layers: 
- VK_LAYER_NV_optimus (1.2.155) : NVIDIA Optimus layer
- VK_LAYER_VALVE_steam_overlay_32 (1.2.136) : Steam Overlay Layer
- VK_LAYER_VALVE_steam_overlay_64 (1.2.136) : Steam Overlay Layer
- VK_LAYER_VALVE_steam_fossilize_32 (1.2.136) : Steam Pipeline Caching Layer
- VK_LAYER_VALVE_steam_fossilize_64 (1.2.136) : Steam Pipeline Caching Layer

Vulkan Devices: 
- [7825] NVIDIA 'GeForce RTX 2070 Super with Max-Q Design' (Discrete GPU: vulkan 1.2.155, driver NVIDIA 460.39 - 460.39.0)

Setting Device [7825]:
- loading '../assets/textures/white.png'... (1 x 1 x 3) 4.325e-05s
- built acceleration structures in 0.0118718s

Swap Chain: 
- image count: 2
- present mode: 2

- loading '../assets/textures/white.png'... (1 x 1 x 3) 1.8575e-05s
- built acceleration structures in 0.00154896s
- loading '../assets/models/lucy.obj'... (673335 vertices, 224491 unique vertices, 1 materials) 0.57441s
- loading '../assets/textures/white.png'... (1 x 1 x 3) 4.0822e-05s
- built acceleration structures in 0.00826155s
FATAL: failed to wait for fence (ERROR_DEVICE_LOST)

 0# void Throw<std::runtime_error>(std::runtime_error const&) in ./RayTracer
 1# Vulkan::Check(VkResult, char const*) [clone .cold] in ./RayTracer
 2# Vulkan::Application::DrawFrame() in ./RayTracer
 3# Vulkan::Window::Run() in ./RayTracer
 4# Vulkan::Application::Run() in ./RayTracer
 5# main in ./RayTracer
 6# __libc_start_main in /usr/lib/libc.so.6
 7# _start in ./RayTracer
```

It appears to be something related to a fence and the device being lost, though that could just be a symptom of something else.

Is it possible that ray-tracing is "partially" broken and that different parts of the GPU or driver are used for these specific two demos which expose the issue and that this is still some kind of hardware issue? It's strange that these two specific demos fail and the others don't. There are also [similar reports on Windows](https://github.com/GPSnoopy/RayTracingInVulkan/issues/26) on the project's issue tracker, but they could be unrelated.
