### ISSUE TITLE
Sound Problem

### ISSUE THREAD

**Issue by maximus105** [NVIDIA/Q2RTX#47] opened 2019-11-27 18:42 UTC
On the maps base3, jail1, jail2, jail3, jail5, lab the sounds of monsters disappear, doors open, gun shots, grenade explosions, etc. It is possible that other cards also have problems with sound. In Quake 2 RTX version 1.1.0 everything worked fine.

**Comment by apanteleev** [comment] 2019-11-27 20:31
Thank you, we're aware of the bug.

It appears to be caused by the `sv_novis 1` setting that the v1.2 engine sets for maps with security cameras. That causes the server to send too many sound entities to the client, and the OpenAL backend runs out of channels.

As a workaround, switch to the software backend (`s_enable 1`) or use `sv_novis 0` after loading one of those maps. This should be fixed soon.

**Comment by apanteleev** [comment] 2019-11-27 22:37
Fixed in commit https://github.com/NVIDIA/Q2RTX/commit/65688c5266a940c12b058d48b40ffc77116173f4

**Closed** 2019-12-02 23:14 UTC
